config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :beneficiary_schemes
  resources :citizens
  resources :departments
  resources :development_works
  resources :entity_statuses
  resources :events
  resources :feedbacks
  resources :notifications do 
    get :current, on: :collection
    get :specific_notification_form, on: :collection
    post :notify_specific_user, on: :collection
  end
  resources :positions
  resources :scheme_types
  resources :valid_types
  
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  resources :districts do 
    collection do
      get :place_form
      get :village_select
      post :create_place
      get :entity_form
      post :create_entity
    end
    member do
      get :panchayat_details
      patch :update_place
      patch :update_entity
    end
  end
  resources :users

  namespace :api do
    namespace :v1 do
      resources :appointments
      resources :beneficiary_schemes, only: [:index, :show]
      resources :commons do
        collection do
          get :status_list
          get :places
          get :departments
        end
      end
      resources :development_works, only: [:index, :show]
      resources :events, only: [:index, :show]
      resources :feedbacks
      resources :users do        
        collection do
          get :exists
          get :is_complete
          get :me
          post :otp
          post :otp_verify
          get :positions
          post :reset_password
          post :sign_in
          delete :sign_out
        end
      end
    end
  end
  
  get "users/suggest", to: "users#suggest"
  get "places/suggest", to: "districts#suggest"
  get "privacy_policy", to: "pages#pp"
  root "pages#index"
end

app/controllers/valid_types_controller.rb
class ValidTypesController < ApplicationController
  before_action :admin_only
  before_action :set_valid_type, only: [:show, :edit, :update, :destroy]

  # GET /valid_types
  # GET /valid_types.json
  def index
    @valid_types = ValidType.all
  end

  # GET /valid_types/1
  # GET /valid_types/1.json
  def show
  end

  # GET /valid_types/new
  def new
    @valid_type = ValidType.new
  end

  # GET /valid_types/1/edit
  def edit
  end

  # POST /valid_types
  # POST /valid_types.json
  def create
    @valid_type = ValidType.new(valid_type_params)
    @valid_type.typed = true

    respond_to do |format|
      if @valid_type.save
        format.html { redirect_to valid_types_path, notice: 'Entity Type was successfully created.' }
        format.json { render :show, status: :created, location: @valid_type }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @valid_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valid_types/1
  # PATCH/PUT /valid_types/1.json
  def update
    respond_to do |format|
      if @valid_type.update(valid_type_params)
        format.html { redirect_to valid_types_path, notice: 'Entity Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @valid_type }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @valid_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valid_types/1
  # DELETE /valid_types/1.json
  def destroy
    @valid_type.destroy
    respond_to do |format|
      format.html { redirect_to valid_types_url, notice: 'Entity status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valid_type
      @valid_type = ValidType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valid_type_params
      params.require(:valid_type).permit(:entity_type, :name, :code, :regional_name_value)
    end
end

app/views/valid_types/_form.html.erb
<%= simple_form_for(@valid_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :entity_type, collection: EntityStatus::VALID_TYPES.values, label: "ಹಾಲಿ ಸ್ಥಿತಿಗಳು" %>
    <%= f.input :regional_name_value, placeholder: "ಕನ್ನಡದಲ್ಲಿ ಹೆಸರು", label: "ಕನ್ನಡದಲ್ಲಿ ಹೆಸರು", input_html: { value: (f.object.regional_name_name rescue "") } %>
    <%= f.input :name, label: "ಹೆಸರು" %>
    <%= f.input :code, label: "ಕೋಡ್" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/valid_types/edit.html.erb
  <div class="content">
    <%= render 'form', entity_status: @entity_status %>
    <%= link_to 'ಹೆಚ್ಚಿನ ವಿವರ', @entity_status %> |
    <%= link_to 'ಹಿಂದೆ', entity_statuses_path %>
  </div>

app/views/valid_types/edit.js.erb
$("#entityModalLabel").html("ಎಡಿಟಿಂಗ್");
$("#entityModalBody").html('<%= j render("form") %>');
$("#entityModal").modal("show");

app/views/valid_types/index.html.erb
<% @module_name = "ವಿಧಗಳ ಮೋಡ್ಯುಲ್" %>

  <div class="content">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <%= link_to 'ಹೊಸ ಹಾಲಿ ಸ್ಥಿತಿ ಸೇರಿಸು', new_valid_type_path, remote: true, class: "btn btn-primary" %>
                  <hr />
          </div>
          <div class="card-body">
            <div class="col-sm">
              <div class="list-group">
                <% @valid_types.group_by{|x| x.entity_type}.each do |e_type, entities| %>
                <div class="list-group-item disabled">
                  <h4>
                    <%= e_type %>
                  </h4>
                </div>
                <% entities.each do |valid_type| %>
                <div class="list-group-item list-group-item-action">
                  <%= valid_type.rgnl_name %>
                  <div class="d-flex float-right" role="group" %>
                    <%= link_to icon('fas', 'edit'), edit_valid_type_path(valid_type), remote: true, class: "btn btn-info btn-sm m-1" %>
                    <%= link_to icon('fas', 'times'), valid_type, method: :delete, remote: true, data: { confirm: 'ನೀವು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ??' }, class: "btn btn-danger btn-sm m-1" %>
                  </div>
                </div>
                <% end %>
                <% end %>
              </div>
            </div>
            <%= render "shared/modal" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/valid_types/new.html.erb
  <div class="content">
    <%= render 'form', entity_status: @entity_status %>
    <%= link_to 'ಹಿಂದೆ', entity_statuses_path %>
  </div>

app/views/valid_types/new.js.erb
$("#entityModalLabel").html("ಸ್ಥಿತಿಯ ವಿಧ");
$("#entityModalBody").html('<%= j render("form") %>');
$("#entityModal").modal("show");

app/views/valid_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ಸ್ಥಿತಿಯ ವಿಧ:</strong>
  <%= @entity_status.entity_type %>
</p>

<p>
  <strong>ಹೆಸರು:</strong>
  <%= @entity_status.name %>
</p>

<p>
  <strong>ಕೋಡ್:</strong>
  <%= @entity_status.code %>
</p>

<%= link_to 'ಎಡಿಟ್', edit_entity_status_path(@entity_status) %> |
<%= link_to 'ಹಿಂದೆ', entity_statuses_path %>