config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :beneficiary_schemes
  resources :citizens
  resources :departments
  resources :development_works
  resources :entity_statuses
  resources :events
  resources :feedbacks
  resources :notifications do 
    get :current, on: :collection
    get :specific_notification_form, on: :collection
    post :notify_specific_user, on: :collection
  end
  resources :positions
  resources :scheme_types
  resources :valid_types
  
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  resources :districts do 
    collection do
      get :place_form
      get :village_select
      post :create_place
      get :entity_form
      post :create_entity
    end
    member do
      get :panchayat_details
      patch :update_place
      patch :update_entity
    end
  end
  resources :users

  namespace :api do
    namespace :v1 do
      resources :appointments
      resources :beneficiary_schemes, only: [:index, :show]
      resources :commons do
        collection do
          get :status_list
          get :places
          get :departments
        end
      end
      resources :development_works, only: [:index, :show]
      resources :events, only: [:index, :show]
      resources :feedbacks
      resources :users do        
        collection do
          get :exists
          get :is_complete
          get :me
          post :otp
          post :otp_verify
          get :positions
          post :reset_password
          post :sign_in
          delete :sign_out
        end
      end
    end
  end
  
  get "users/suggest", to: "users#suggest"
  get "places/suggest", to: "districts#suggest"
  get "privacy_policy", to: "pages#pp"
  root "pages#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :title, :content, :expiry, presence: true  

  scope :active, ->{where("expiry >= ?", Date.today).order(created_at: :desc)}

  after_commit :push_out

  def notify
    ActionCable.server.broadcast('web_notifications_channel', 
      heading: self.title, body: self.content)
  end

  def notify_specific_user(reciever_id)
    ActionCable.server.broadcast("web_notifications_channel_#{reciever_id}",
      heading: self.title, body: self.content)
  end

  private
    def push_out
      notify if self.push
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :admin_only
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end
def specific_notification_form
    @notification = Notification.new  
  end

  # POST /notifications/notify_in
  def notify_specific_user
    # redirect_to notifications_path, notice: "created successfully."
    @notification = Notification.new(notification_params)
    @notification.user = current_user
    reciever = User.find(params[:reciever_id])

    respond_to do |format|
      if @notification.save
        @notification.notify_specific_user(reciever.id)
        format.html { redirect_to notifications_path, notice: 'Notification was successfully created.'}
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /notifications/current
  def current
    @notifications = Notification.active
    render partial: "current"
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    @notification.user = current_user

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notifications_path, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notifications_path, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :content, :mail, :phone, :push, :expiry, :reciever_id)
    end
end

app/views/notifications/_current.html.erb
<div class="list-group">
  <% @notifications.each do |n| %>
    <div  class="list-group-item">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= n.title %></h5>
        <small><%= time_ago_in_words(n.created_at) %> ago</small>
      </div>
      <p class="mb-1"><%= n.content %></p>
    </div>
  <% end %>
</div>

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification, remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <div class="row">
      <div class="col-4"><%= f.input :mail %></div>
      <div class="col-4"><%= f.input :phone %></div>
      <div class="col-4"><%= f.input :push, default: true %></div>
    </div>
    <%= f.input :expiry, as: :string %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  $('#notification_expiry').datepicker(modalDateConfig);
</script>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'ಹೆಚ್ಚಿನ ವಿವರ', @notification %> |
<%= link_to 'ಹಿಂದೆ', notifications_path %>

app/views/notifications/edit.js.erb
$("#entityModalLabel").html("ಎಡಿಟಿಂಗ್");
$("#entityModalBody").html('<%= j render("form") %>');
$("#entityModal").modal("show");

app/views/notifications/index.html.erb
<div class="content">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <%= link_to 'New Notification', new_notification_path, id: :new_dept, remote: true, class: "btn btn-primary" if current_user.admin? %>
          <%= link_to 'Notify Specific User', specific_notification_form_notifications_path, class: "btn btn-primary" %>
          <hr/>
        </div>
        <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>ಶೀರ್ಷಿಕೆ</th>
                <th>ವಿಷಯ</th>
                <th>Modes</th>
                <th>ಕ್ರಮಗಳು</th>
              </tr>
            </thead>

            <tbody>
              <% @notifications.each do |notification| %>
                <tr>
                  <td><%= notification.title %></td>
                  <td><%= notification.content %></td>
                  <td>
                    <ul>
                      Mail <%= '<i class="fa fa-check" aria-hidden="true"></i>'.html_safe if notification.mail %><br/>
                      Phone<%= '<i class="fa fa-check" aria-hidden="true"></i>'.html_safe if notification.phone %> <br/>
                      Push <%= '<i class="fa fa-check" aria-hidden="true"></i>'.html_safe if notification.push %><br/>
                    </ul>
                  </td>
                  <td>
                    <div class="d-flex float-right" role="group" %>
                      <%= link_to icon('fas', 'edit'), edit_notification_path(notification), remote: true, class: "btn btn-info btn-sm m-1" %>
                      <%= link_to icon('fas', 'times'), notification, method: :delete, remote: true, data: { confirm: 'ನೀವು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ??' }, class: "btn btn-danger btn-sm m-1" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <%= render "shared/modal" %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'ಹಿಂದೆ', notifications_path %>

app/views/notifications/new.js.erb
$("#entityModalLabel").html("New Notification");
$("#entityModalBody").html('<%= j render("form") %>');
$("#entityModal").modal("show");

app/views/notifications/show.html.erb
<p>
  <strong>ಟೈಟಲ್:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>ವಿಷಯ:</strong>
  <%= @notification.content %>
</p>
<h4> Forms of delivery</h4>
<p>
  <strong>ಇ.ಮೇಲ್:</strong>
  <%= @notification.mail %>
</p>

<p>
  <strong>ಪೋನ ನಂಬರ:</strong>
  <%= @notification.phone %>
</p>

<p>
  <strong>ಆಮಂತ್ರಣ ಕಳುಹಿಸು:</strong>
  <%= @notification.push %>
</p>


<%= link_to 'ಎಡಿಟ್', edit_notification_path(@notification) %> |
<%= link_to 'ಹಿಂದೆ', notifications_path %>

app/views/notifications/specific_notification_form.html.erb
<%= simple_form_for(@notification, remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="padding" style="padding-bottom: 80px">
</div>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <div class="row">
      <div class="col-4"><%= f.input :mail %></div>
      <div class="col-4"><%= f.input :phone %></div>
      <div class="col-4"><%= f.input :push, default: true %></div>
    </div>
    <%= f.input :expiry, as: :string %>
  </div>
  <%= select_tag "reciever_id", options_from_collection_for_select(User.all, "id", "name"), class: "form-control" %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  $('#notification_expiry').datepicker(modalDateConfig);
</script>