config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :beneficiary_schemes
  resources :citizens
  resources :departments
  resources :development_works
  resources :entity_statuses
  resources :events
  resources :feedbacks
  resources :notifications do 
    get :current, on: :collection
    get :specific_notification_form, on: :collection
    post :notify_specific_user, on: :collection
  end
  resources :positions
  resources :scheme_types
  resources :valid_types
  
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  resources :districts do 
    collection do
      get :place_form
      get :village_select
      post :create_place
      get :entity_form
      post :create_entity
    end
    member do
      get :panchayat_details
      patch :update_place
      patch :update_entity
    end
  end
  resources :users

  namespace :api do
    namespace :v1 do
      resources :appointments
      resources :beneficiary_schemes, only: [:index, :show]
      resources :commons do
        collection do
          get :status_list
          get :places
          get :departments
        end
      end
      resources :development_works, only: [:index, :show]
      resources :events, only: [:index, :show]
      resources :feedbacks
      resources :users do        
        collection do
          get :exists
          get :is_complete
          get :me
          post :otp
          post :otp_verify
          get :positions
          post :reset_password
          post :sign_in
          delete :sign_out
        end
      end
    end
  end
  
  get "users/suggest", to: "users#suggest"
  get "places/suggest", to: "districts#suggest"
  get "privacy_policy", to: "pages#pp"
  root "pages#index"
end

app/views/shared/_date_selector.html.erb
<div class="col-md-3 col-sm-12 my-2">
  <%= text_field_tag :start_date, params[:start_date], class: "input form-control", placeholder: "ಪ್ರಾರಂಭ ದಿನಾಂಕ" %>
</div>
<div class="col-md-3 col-sm-12 my-2">
  <%= text_field_tag :end_date, params[:end_date], class: "input form-control", placeholder: "ಮುಕ್ತಾಯ ದಿನಾಂಕ " %>
</div>
<script type="text/javascript">
  $('#start_date').datepicker(dateConfig);
  $('#end_date').datepicker(dateConfig);
</script>

app/views/shared/_document_uploader.html.erb
<div class="row mb-4 alert alert-warning">
  <div class="col-6 justify-content-center align-self-center"><h6> ಸಂಭಂದಿಸಿದ ದಾಖಲೆ <%= f.object.class.to_s %> </h6></div>
  <div class="col-6"><%= f.link_to_add "+ ದಾಖಲೆಗಳನ್ನು ಸೇರಿಸಿ", :stored_files, :data => { :target => "#documentsHolder" }, class: "btn btn-md btn-primary float-right m-0" %>
  </div>
</div>
<div class="col-12">
  <div class="card-group" id="documentsHolder">
    <%= f.simple_fields_for :stored_files do |g| %>
      <div class="card border" style="width: 18rem;">
        <div class="card-body">
          <%= link_to g.object.document.file.filename, g.object.document_url,  style: "padding:5px;" if g.object.document.present? %>
          <%= g.input :document %>
          <%= g.hidden_field :document_cache %>
          <%= g.input :desc %>
        </div>
        <div class="card-footer">
          <%= g.link_to_remove "ಡಿಲಿಟ್", class: "btn btn-outline-danger btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
    <footer class="footer footer-black  footer-white d-sm-none d-md-block">
      <div class="container-fluid">
        <div class="row">
          <nav class="footer-nav">
            <ul>
              <li>
                <a href="/" target="_blank">Zone Manager</a>
              </li>
              <li>
                <a href="http://nighthack.in/" target="_blank">Powered by <strong class="text-uppercase">Nighthack Labs</strong></a>
              </li>
            </ul>
          </nav>
          <div class="credits ml-auto">
            <span class="copyright">
             ©2019 SunilNaik, MLA, Bhatkal
            </span>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_header.html.erb
<% if current_user %>
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-minimize">
        <button id="minimizeSidebar" class="btn btn-icon btn-round btn-primary">
          <i class="fa fa-bars text-center visible-on-sidebar-mini"></i>
          <i class="fa fa-bars text-center visible-on-sidebar-regular"></i>
        </button>
      </div>
      <div class="navbar-toggle">
        <button type="button" class="navbar-toggler">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <div class="navbar-brand text-white">
        <%= title if defined?(title) %>
      </div>
    </div>
  </div>
</nav>
<% end %>
<script>
$(document).ready(function() {
    paperDashboard = {
        misc: {
            navbar_menu_visible: 0
        },
    };
     $('html').removeClass('nav-open');
      setTimeout(function() {
          $('.navbar-toggle').removeClass('toggled');
          $('#bodyClick').remove();
      }, 550);
    $('#minimizeSidebar').click(function() {
        var $btn = $(this);
        const $body = $('body');
        $body.toggleClass('sidebar-mini');
        // we simulate the window Resize so the charts will get updated in realtime.
        var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
        }, 180);

        // we stop the simulation of Window Resize after the animations are completed
        setTimeout(function() {
            clearInterval(simulateWindowResize);
        }, 1000);
    });
    $('.navbar-toggle').click(function() {
        $toggle = $(this);
        if (paperDashboard.misc.navbar_menu_visible == 1) {
            $('html').removeClass('nav-open');
            paperDashboard.misc.navbar_menu_visible = 0;
            setTimeout(function() {
                $toggle.removeClass('toggled');
                $('#bodyClick').remove();
            }, 550);

        } else {
            setTimeout(function() {
                $toggle.addClass('toggled');
            }, 580);

            div = '<div id="bodyClick"></div>';
            $(div).appendTo('body').click(function() {
                $('html').removeClass('nav-open');
                paperDashboard.misc.navbar_menu_visible = 0;
                setTimeout(function() {
                    $toggle.removeClass('toggled');
                    $('#bodyClick').remove();
                }, 550);
            });

            $('html').addClass('nav-open');
            paperDashboard.misc.navbar_menu_visible = 1;
        }
    });
});

</script>

app/views/shared/_image_uploader.html.erb
<div class="col-12">
  <div class="row mb-4 alert alert-warning">
    <div class="col-6 justify-content-center align-self-center">
      <h6> ಪೋಟೋ ಲಗತ್ತಿಸು </h6>
    </div>
    <div class="col-6">
      <%= f.link_to_add "+ ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಿ", :stored_images, :data => { :target => "#imagesHolder" }, class: "btn btn-md btn-primary float-right m-0" %>
    </div>
  </div>
  <div class="card-group" id="imagesHolder">
    <%= f.simple_fields_for :stored_images do |g| %>
    <div class="card border" style="width: 18rem;">
      <%= image_tag g.object.image_url(:thumb), class: "card-img-top", style: "padding:5px;" if g.object.image.present? %>
      <div class="card-body">
        <%= g.input :image %>
        <%= g.hidden_field :image_cache %>
        <%= g.input :desc %>
      </div>
      <div class="card-footer">
        <%= g.link_to_remove "ಡಿಲಿಟ್", class: "btn btn-outline-danger btn-sm" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<style type="text/css">
  /* fix bootstrap-datepicker positional bug */
  .modal-body .datepicker {
    transform: translate(3.1em, 0);
  }
</style>
<!-- Modal -->
<div class="modal fade" id="entityModal" tabindex="-1" role="dialog" aria-labelledby="entityModalLabel" aria-hidden="true">
  <div class="modal-dialog <%= "modal-lg" if defined?(large) %>" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="entityModalLabel">Editing Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="entityModalBody">
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav_links.html.erb
<!-- Holder for Capabilities -->
<div class="bjp-bg">
  <div class="container-fluid text-center" style="min-height: 300px; padding:4%;">
    <div class="card border-warning card-trans mt-2">
      <div class="col-md-12 col-sm-12">
        <div class="card-body">
          <h5 class="card-title">ನಾಗರಿಕರ ನೋಂದಣಿ</h5>
          <h6 class="card-subtitle mb-2">Register to Have Full Access Online</h6>
        </div>
        <div class="card-footer"><%= link_to "Register Now", "", class: "btn btn-outline-warning" %></div>
      </div>
    </div>
    <div class="row card-deck">
      <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body"><%= link_to development_works_path, class: "btn btn-outline-dark float-right" do %><%= icon("fas","external-link-alt") %><% end %>
            <h5 class="card-title">ದೂರು/ಬೇಡಿಕೆ/ಸಲಹೆ</h5>
            <h6 class="card-subtitle mb-2">Never Hesitate to Complian/Suggest</h6>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body">
            <h5 class="card-title">ಶಾಸಕರ ಕಾರ್ಯಕ್ರಮ ಸಮಯ ನಿಗದಿ</h5>
            <h6 class="card-subtitle mb-2">Book Appointement Online</h6>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body">
            <h5 class="card-title">ಶಾಸಕರ ಕಾರ್ಯಕ್ರಮ/ದಿನಚರಿ</h5>
            <h6 class="card-subtitle mb-2">MLA Program and Events</h6>
          </div>
        </div>
      </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body">
            <h5 class="card-title">ಅಭಿವೃಧ್ಧಿ ಕಾಮಗಾರಿ</h5>
            <h6 class="card-subtitle mb-2">Know Your Area Work Status</h6>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body">
            <h5 class="card-title">ಯೋಜನೆಗಳ ಫಲಾನುಭವಿ ಅರ್ಜಿ ಸ್ಥಿತಿ</h5>
            <h6 class="card-subtitle mb-2">Know Your Application Status</h6>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card card-trans border-warning">
          <div class="card-body">
            <h5 class="card-title">ಉಪಯುಕ್ತ ಮಾಹಿತಿಗಳ ಕೊಂಡಿ</h5>
            <h6 class="card-subtitle mb-2">Useful Information Links</h6>
          </div>
        </div>
      </div>
    </div>
    <div class="card border-warning card-trans mt-2">
      <div class="col-md-12 col-sm-12">
        <div class="card-body">
          <h5 class="card-title">ಅಪ್ಲಿಕೇಶನ್ ಡೌನ್ಲೋಡ್ ಮಾಡಿ</h5>
          <h6 class="card-subtitle mb-2">Download the App today</h6>
          <a href='https://play.google.com/store/apps/details?id=com.sunilnaik&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png'/ style="max-height: 80px;"></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_notify_modal.html.erb
<div class="modal fade" id="notifyModal" tabindex="-1" role="dialog" aria-labelledby="notifyModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="notifyModalHeading">Notification</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="notifyModalBody">
        <center><b><small>This is a System Notification</small></b></center>
      </div>
      <div class="modal-footer" style="justify-content: center;">
        <b><small>This is a System Notification</small></b>
      </div>
    </div>
  </div>
</div>

app/views/shared/_place_selector.html.erb
<div class="col-md-3 col-sm-12 my-2">
  <%= select_tag :panchayat_id, options_from_collection_for_select(Panchayat.external.order(:name), "id", "rgnl_name", params[:panchayat_id]), prompt: "ಪಂಚಾಯತವಾರು ಹುಡುಕು", class: "select form-control  w-100" %>
</div>
<div id="villageSelector" class="col-md-3 col-sm-12 my-2">
  <%= render "shared/village_selector", locals: {villages: Place.where(panchayat_id: params[:panchayat_id]).order(:name)} %>
</div>

<script type="text/javascript">
  // setPanchayatListener();
  $("#panchayat_id").change(function(){
    var panch_id = $(this).val();
    $("#villageSelector").load("<%= village_select_districts_path %>?panchayat_id="+panch_id);
  });
</script>

app/views/shared/_places_suggest.html.erb
<%= label_tag :place, "ಗ್ರಾಮ/ವಾರ್ಡ/ಮಜಿರೆ*", required: true %>
<div class="form-row">
  <div class="col-11">
    <%= text_field_tag :palce, (f.object.place.panch_name rescue ""), id: :place_search, autocomplete: :off, placeholder: "ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ ", class: "input form-control", required: true %>
  </div>
  <div class="col-1 m-0">
    <div id="editPlaceSelect" class="btn btn-info btn-sm"><%= icon('fas', 'edit') %></div>
  </div>
</div>
<%= f.input :place_id, as: :hidden %>
<div class="col">
  <div id="popPlaceContent" class="list-group"></div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar" data-color="brown" data-active-color="danger">
  <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
  <div class="logo">
    <a href="/" class="simple-text logo-mini">
      <div class="logo-image-small">
        <img src="<%= image_url("logo_small.png") %>">
      </div>
    </a>
    <a href="/" class="simple-text logo-normal">
      ಸುನಿಲ ನಾಯ್ಕ, <br />ಶಾಸಕರು 
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <% if user_signed_in? %>
      <% if (current_user.admin? rescue false) %>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= citizens_path %>">
          <i class="fa fa-user"></i>
          <p>
            <span class="d-md-block">ನೋಂದಾಯಿತ ನಾಗರಿಕರು</span>
          </p>
        </a>
      </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= development_works_path %>">
          <i class="fas fa-hard-hat"></i>
          <p>
            <span class="d-md-block">ಅಭಿವೃಧ್ಧಿ ಕಾಮಗಾರಿ</span>
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= beneficiary_schemes_path %>">
          <i class="fas fa-wallet"></i>
          <p>
            <span class="d-md-block">ಫಲಾನುಭವಿಗಳು</span>
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= events_path %>">
          <i class="fas fa-calendar-week"></i>
          <p>
            <span class="d-md-block">ದಿನಂಪ್ರತಿ ಕಾರ್ಯಕ್ರಮಗಳು</span>
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= feedbacks_path %>">
          <i class="fas fa-comments"></i>
          <p>
            <span class="d-md-block">ದೂರು/ಬೇಡಿಕೆ/ಸಲಹೆ</span>
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn-magnify" href="<%= appointments_path %>">
          <i class="fas fa-calendar-check"></i>
          <p>
            <span class="d-md-block">ಸಮಯಾವಕಾಶ ಕೋರಿಕೆ</span>
          </p>
        </a>
      </li>
      <li>
        <a data-toggle="collapse" href="#tablesExamples" class="collapsed" aria-expanded="false">
          <i class="fas fa-cogs"></i>
          <p>
            ಇತರೆ ಮೊಡ್ಯುಲಗಳು
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse" id="tablesExamples" style="">
          <ul class="nav">
            <li>
              <%= link_to "ಇಲಾಖೆ", departments_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "ಹಾಲಿ ಸ್ಥಿತಿ", entity_statuses_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "ವಿಧಗಳ ಮೋಡ್ಯುಲ್", valid_types_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "ಯೋಜನೆ ವಿಧ", scheme_types_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "ಉದ್ಯೋಗ/ಹುದ್ದೆ", positions_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "ಕ್ಷೇತ್ರ ನಿರ್ವಹಣೆ", districts_path, class: "dropdown-item" %>
            </li>
          </ul>
        </div>
      </li>

      <% end %>
    </ul>
    <div class="nav-item my-2 my-lg-0">
      <%= link_to('ಲಾಗ್‌ ಔಟ', destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline btn-primary m-2") %>
    </div>
  </div>
</div>

app/views/shared/_users_suggest.html.erb
<%= label_tag :citizen %>
<div class="form-row">
  <div class="col-11">
    <%= text_field_tag :user, (f.object.user.name rescue ""), id: :user_search, autocomplete: :off, placeholder: "ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ ", class: "input form-control", required: true %>
  </div>
  <div class="col-1">
    <div id="editUserSelect" class="btn btn-info"><%= icon('fas', 'edit') %></div>
  </div>
</div>
<%= f.input :user_id, as: :hidden %>
<div class="col">
  <div id="popUserContent" class="list-group"></div>
</div>

<script type="text/javascript">
  function addUser(){
    window.open("<%= users_path %>")
  }
</script>

app/views/shared/_village_selector.html.erb
<%= select_tag :place_id, options_from_collection_for_select(Place.where(panchayat_id: params[:panchayat_id]).order(:name), "id", "rgnl_name", params[:place_id]), prompt: "ಗ್ರಾಮವಾರು ಹುಡುಕು", class: "select form-control w-100" %>