config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :beneficiary_schemes
  resources :citizens
  resources :departments
  resources :development_works
  resources :entity_statuses
  resources :events
  resources :feedbacks
  resources :notifications do 
    get :current, on: :collection
    get :specific_notification_form, on: :collection
    post :notify_specific_user, on: :collection
  end
  resources :positions
  resources :scheme_types
  resources :valid_types
  
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  resources :districts do 
    collection do
      get :place_form
      get :village_select
      post :create_place
      get :entity_form
      post :create_entity
    end
    member do
      get :panchayat_details
      patch :update_place
      patch :update_entity
    end
  end
  resources :users

  namespace :api do
    namespace :v1 do
      resources :appointments
      resources :beneficiary_schemes, only: [:index, :show]
      resources :commons do
        collection do
          get :status_list
          get :places
          get :departments
        end
      end
      resources :development_works, only: [:index, :show]
      resources :events, only: [:index, :show]
      resources :feedbacks
      resources :users do        
        collection do
          get :exists
          get :is_complete
          get :me
          post :otp
          post :otp_verify
          get :positions
          post :reset_password
          post :sign_in
          delete :sign_out
        end
      end
    end
  end
  
  get "users/suggest", to: "users#suggest"
  get "places/suggest", to: "districts#suggest"
  get "privacy_policy", to: "pages#pp"
  root "pages#index"
end

app/models/beneficiary_scheme.rb
class BeneficiaryScheme < ApplicationRecord
  include Documented
  include Imaged

  belongs_to :place
  belongs_to :scheme_type
  belongs_to :entity_status
  belongs_to :user, optional: true

  validates :scheme_type, :application_date, :beneficiary_name, :beneficiary_phone, presence: true
  before_save :associate_user

  private
    def associate_user
      self.user = User.find_by(phone: beneficiary_phone) rescue nil
    end

end

app/controllers/api/v1/beneficiary_schemes_controller.rb
class Api::V1::BeneficiarySchemesController < Api::BaseController
  def index
    schemes = BeneficiaryScheme.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    render json: schemes.map{|x| 
      {
        "id": x.id,
        "place": x.place.panch_name,
        "scheme_type": x.scheme_type.rgnl_name,
        "beneficiary_phone": x.beneficiary_phone,
        "beneficiary_name": x.beneficiary_name,
        "application_date": x.application_date,
        "granted_relief": x.granted_relief,
        "status": (x.entity_status.rgnl_name rescue "NA"),
        "remarks": x.remarks,
        "created_at": x.created_at,
        "image": x.image_url
      }
    }
  end

  def show
    scheme = BeneficiaryScheme.find(params[:id])
    render json: {
      "id": scheme.id,
      "place": scheme.place.panch_name,
      "scheme_type": scheme.scheme_type.rgnl_name,
      "beneficiary_phone": scheme.beneficiary_phone,
      "beneficiary_name": scheme.beneficiary_name,
      "application_date": scheme.application_date,
      "granted_relief": scheme.granted_relief,
      "status": (scheme.entity_status.rgnl_name rescue "NA"),
      "remarks": scheme.remarks,
      "created_at": scheme.created_at,
      "images": scheme.stored_images.map{|x| x.image_url}
    }
  end
end

app/controllers/beneficiary_schemes_controller.rb
class BeneficiarySchemesController < ApplicationController
  before_action :set_beneficiary_scheme, only: [:show, :api_show, :edit, :update, :destroy]


  # GET /beneficiary_schemes
  # GET /beneficiary_schemes.json
  def index
    handle_pages
    @beneficiary_schemes = BeneficiaryScheme.all
    @beneficiary_schemes = @beneficiary_schemes.where("beneficiary_name RLIKE (?)", params[:search].to_s) unless params[:search].blank?
    @beneficiary_schemes = @beneficiary_schemes.joins(:place).
      where("places.panchayat_id" => params[:panchayat_id]) unless params[:panchayat_id].blank?
    @beneficiary_schemes = @beneficiary_schemes.where(place_id: params[:place_id]) unless params[:place_id].blank?
    @beneficiary_schemes = @beneficiary_schemes.where(scheme_type_id: params[:scheme_type_id]) unless params[:scheme_type_id].blank?
    @beneficiary_schemes = @beneficiary_schemes.where(entity_status_id: params[:status_id]) unless params[:status_id].blank?

    if params[:start_date].present? or params[:end_date].present?        
      start_date = params[:start_date].blank? ? Date.today : params[:start_date]
      end_date = params[:end_date].blank? ? Date.today+7.days : params[:end_date]
      @beneficiary_schemes = @beneficiary_schemes.where("application_date >= ? and application_date <= ?",start_date, end_date)
    end

    @beneficiary_schemes = @beneficiary_schemes.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /beneficiary_schemes/1
  # GET /beneficiary_schemes/1.json
  def api_show
    render partial: "show"
  end

  # GET /beneficiary_schemes/1
  # GET /beneficiary_schemes/1.json
  def show
  end

  # GET /beneficiary_schemes/new
  def new
    @beneficiary_scheme = BeneficiaryScheme.new
  end

  # GET /beneficiary_schemes/1/edit
  def edit
  end

  # POST /beneficiary_schemes
  # POST /beneficiary_schemes.json
  def create
    @beneficiary_scheme = BeneficiaryScheme.new(beneficiary_scheme_params)

    respond_to do |format|
      if @beneficiary_scheme.save
        format.html { redirect_to beneficiary_schemes_path(page: prev_page), notice: 'Beneficiary scheme was successfully created.' }
        format.json { render :show, status: :created, location: @beneficiary_scheme }
      else
        format.html { render :new }
        format.json { render json: @beneficiary_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiary_schemes/1
  # PATCH/PUT /beneficiary_schemes/1.json
  def update
    respond_to do |format|
      if @beneficiary_scheme.update(beneficiary_scheme_params)
        format.html { redirect_to beneficiary_schemes_path(page: prev_page), notice: 'Beneficiary scheme was successfully updated.' }
        format.json { render :show, status: :ok, location: @beneficiary_scheme }
      else
        format.html { render :edit }
        format.json { render json: @beneficiary_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiary_schemes/1
  # DELETE /beneficiary_schemes/1.json
  def destroy
    @beneficiary_scheme.destroy
    respond_to do |format|
      format.html { redirect_to beneficiary_schemes_path(page: prev_page), notice: 'Beneficiary scheme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiary_scheme
      @beneficiary_scheme = BeneficiaryScheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiary_scheme_params
      params.require(:beneficiary_scheme).permit(:place_id, :scheme_type_id, :entity_status_id, :beneficiary_name, 
        :beneficiary_phone, :application_date, :granted_relief, :status, :remarks,
          stored_file_whitelist, stored_image_whitelist)
    end
end

app/helpers/api/v1/beneficiary_schemes_helper.rb
module Api::V1::BeneficiarySchemesHelper
end

app/helpers/beneficiary_schemes_helper.rb
module BeneficiarySchemesHelper
end

app/views/beneficiary_schemes/_form.html.erb
<div class="container">
  <%= simple_nested_form_for(@beneficiary_scheme) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= render "shared/places_suggest", f: f %>
    <%= f.input :beneficiary_phone, as: :integer, label: 'ಫಲಾನುಭವಿಗಳ ಪೋನ್‌ ನಂಬರ' %>
    <%= f.input :beneficiary_name, label: 'ಫಲಾನುಭವಿಗಳ ಹೆಸರು' %>
    <%= f.association :scheme_type, label_method: :rgnl_name, label: 'ಯೋಜನೆ ವಿಧ' %>
    <%= f.input :application_date, label: 'ಅರ್ಜಿ ದಿನಾಂಕ' %>
    <%= f.input :granted_relief, label: 'ಮಂಜೂರಾದ ಪರಿಹಾರ' %>
    <%= f.association :entity_status, label: "ಹಾಲಿ ಸ್ಥಿತಿ", collection: EntityStatus.where(entity_type: f.object.class.to_s), label_method: :rgnl_name %>
    <%= f.input :remarks, label: 'ಷರಾ'%>
  </div>
  <hr />
  <%= render "shared/document_uploader", f: f %>
  <hr />
  <%= render "shared/image_uploader", f: f %>
  <hr />
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
  <% end %>
  <script type="text/javascript">
  // Set autosuggest on this module
  setPlaceSuggester("<%= places_suggest_path %>", "beneficiary_scheme");

  </script>
</div>

app/views/beneficiary_schemes/edit.html.erb
<% @module_name = "ಫಲಾನುಭವಿಗಳು > ಎಡಿಟಿಂಗ್" %>
<div class="content">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <%= link_to 'ಹೆಚ್ಚಿನ ವಿವರ', @beneficiary_scheme %> |
          <%= link_to 'ಹಿಂದೆ', beneficiary_schemes_path %>
          <hr />
        </div>
        <div class="card-body">
          <%= render 'form', beneficiary_scheme: @beneficiary_scheme %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/beneficiary_schemes/index.html.erb
<% @module_name = "ಫಲಾನುಭವಿಗಳು" %>
<div class="content">
  <div class="card">
    <div class="card-header">
      <%= link_to 'ಹೊಸ ಫಲಾನುಭವಿ ಸೇರಿಸು', new_beneficiary_scheme_path, class: "btn btn-primary" if current_user.admin? %>
      <hr />
    </div>
    <div class="card-body">
      <div class="row mt-2">
        <div class="container-fluid">
          <%= form_tag({},{method: :get}) do %>
          <div class="row">
            <div class="col-md-3 col-sm-12 my-2">
              <%= text_field_tag :search, params[:search], class: "input form-control", placeholder: "ಫಲಾನುಭವಿಗಳ ಹೆಸರಿನಿಂದ ಹುಡುಕು" %>
            </div>
            <%= render "shared/place_selector" %>
            <div class="col-md-3 col-sm-12 my-2">
              <%= select_tag :status_id, options_from_collection_for_select(EntityStatus.where(entity_type: "BeneficiaryScheme"), "id", "rgnl_name", params[:status_id]), prompt: "ಹಾಲಿ ಸ್ಥಿತಿ ಮೇಲೆ ಫಲಾನುಭವಿ ಪರಿಷ್ಕರಿಸು", class: "form-control select w-100" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 col-sm-12 my-2">
              <%= select_tag :scheme_type_id, options_from_collection_for_select(SchemeType.all, "id", "rgnl_name",params[:scheme_type_id]), prompt: "ಸ್ಕೀಮ್ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ", class: "select form-control w-100" %>
            </div>
            <%= render "shared/date_selector" %>            
            <div class="col-md-3 col-sm-12">
              <%= submit_tag :ಹುಡುಕು, class: "btn btn-warning btn-sm" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col">
          <center><h4><%= @beneficiary_schemes.count %> ಫಲಾನುಭವಿಗಳು</h4></center>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ಕ್ರಮ ಸಂಖ್ಯೆ</th>
              <th>ನೋಂದಾಯಿತ ನಾಗರಿಕರು</th>
              <th>ಸ್ಥಳ</th>
              <th>ಯೋಜನೆ ವಿಧ</th>
              <th>ಅರ್ಜಿ ದಿನಾಂಕ</th>
              <th>ಮಂಜೂರಾದ ಪರಿಹಾರ</th>
              <th>ಹಾಲಿ ಸ್ಥಿತಿ</th>
              <th>ಷರಾ</th>
              <% if current_user.admin? %>
              <th>ಕ್ರಮಗಳು</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% page = params[:page].present? ? (params[:page].to_i rescue 1) : 1 %>
            <% @beneficiary_schemes.each_with_index do |beneficiary_scheme, ix| %>
            <tr>
              <td>
                <%= (page -1) * 10 + (ix+1) %>
              </td>
              <td>
                <%= beneficiary_scheme.beneficiary_name %> :
                <%= beneficiary_scheme.beneficiary_phone %>
              </td>
              <td>
                <%= beneficiary_scheme.place.panch_name %>
              </td>
              <td>
                <%= beneficiary_scheme.scheme_type.rgnl_name %>
              </td>
              <td>
                <%= beneficiary_scheme.application_date.strftime("%d-%m-%Y") rescue "NA" %>
              </td>
              <td>
                <%= beneficiary_scheme.granted_relief %>
              </td>
              <td>
                <%= beneficiary_scheme.entity_status.rgnl_name %>
              </td>
              <td>
                <%= beneficiary_scheme.remarks %>
              </td>
              <% if current_user.admin? %>
              <td>
                <div class="d-flex" role="group">
                  <%= link_to 'ಹೆಚ್ಚಿನ ವಿವರ', beneficiary_scheme, class: "btn btn-sm btn-info m-2" %>
                  <%= link_to 'ಎಡಿಟ್', edit_beneficiary_scheme_path(beneficiary_scheme), class: "btn btn-sm btn-primary m-2" %>
                  <%= link_to 'ಡಿಲಿಟ್', beneficiary_scheme, method: :delete, data: { confirm: 'ನೀವು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ??' }, class: "btn btn-sm btn-danger m-2" %>
                </div>
              </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer align-self-center ">
      <center>
        <%= will_paginate @beneficiary_schemes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </center>
    </div>
  </div>
</div>

app/views/beneficiary_schemes/new.html.erb
<div class="content">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <%= render 'form', beneficiary_scheme: @beneficiary_scheme %>
        </div>
        <div class="card-footer">
          <%= link_to 'ಹಿಂದೆ', beneficiary_schemes_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/beneficiary_schemes/show.html.erb
<% @module_name = "ಫಲಾನುಭವಿಗಳು > ವಿವರಗಳು" %>
<div class="content">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <%= link_to 'ಎಡಿಟ್', edit_beneficiary_scheme_path(@beneficiary_scheme) %> |
          <%= link_to 'ಹಿಂದೆ', beneficiary_schemes_path %>
          <hr />
        </div>
        <div class="card-body">
          <div class="container table-responsive">
            <table class="table table-striped table-hover">
              <tr>
                <td><strong>ಸ್ಥಳ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.place.rgnl_name %>
                </td>
              </tr>
              <tr>
                <td><strong>ಯೋಜನೆ ವಿಧ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.scheme_type.rgnl_name %>
                </td>
              </tr>
              <tr>
                <td><strong>ನಾಗರಿಕರ ಹೆಸರು:</strong></td>
                <td>
                  <%= @beneficiary_scheme.beneficiary_name %> :
                  <%= @beneficiary_scheme.beneficiary_phone %>
                </td>
                </td>
              </tr>
              <tr>
                <td><strong>ಅರ್ಜಿ ದಿನಾಂಕ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.application_date %>
                </td>
              </tr>
              <tr>
                <td><strong>ಮಂಜೂರಾದ ಪರಿಹಾರ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.granted_relief %>
                </td>
              </tr>
              <tr>
                <td><strong>ಹಾಲಿ ಸ್ಥಿತಿ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.entity_status.rgnl_name %>
                </td>
              </tr>
              <tr>
                <td><strong>ಷರಾ:</strong></td>
                <td>
                  <%= @beneficiary_scheme.remarks %>
                </td>
              </tr>
              <tr>
                <td><strong>ದಾಖಲೆ ಲಗತ್ತಿಸು:</strong></td>
                <td>
                  <div class="list-group">
                    <% @beneficiary_scheme.stored_files.each do |d| %>
                    <%= link_to d.document_url, class: "list-group-item" do %>
                    <%= d.document.file.filename %> :
                    <%= d.desc %>
                    <% end %>
                    <% end %>
                  </div>
                </td>
              </tr>
            </table>
          </div>
          <div class="container mt-5">
            <h6 class="alert alert-success"> ಪೋಟೋ ಲಗತ್ತಿಸು </h6>
            <div class="row">
              <% @beneficiary_scheme.stored_images.each do |i| %>
              <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="card border" style="width: 20rem;">
                  <%= image_tag i.image_url(:thumb), class: "card-img-top img-thumbnail", style: "padding:5px;" %>
                  <div class="card-body">
                    <%= i.desc %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>